tern:
    # TO PUBLISH ALL JOINT STATES
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
    left_motor_controller:
        type: effort_controllers/JointVelocityController
        joint: left_rotor_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
    right_motor_controller:
        type: effort_controllers/JointVelocityController
        joint: right_rotor_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}    
    left_elevon_controller:
        type: effort_controllers/JointPositionController
        joint: left_elevon_joint
        pid: {p: 100.0, i: 0.1, d: 10.0}
    right_elevon_controller:
        type: effort_controllers/JointPositionController
        joint: right_elevon_joint
        pid: {p: 100.0, i: 0.1, d: 10.0}
